// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti;

namespace RS1_MVC_Transportno_Preduzece_core_web_app.Migrations
{
    [DbContext(typeof(MojDBcontexV2))]
    [Migration("20211218094007_InicijalnaDB_v6")]
    partial class InicijalnaDB_v6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.Dostavnica", b =>
                {
                    b.Property<int>("DostavnicaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrojDostavnice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Datum_realizacije")
                        .HasColumnType("datetime2");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DostavnicaID");

                    b.ToTable("Dostavnica");
                });

            modelBuilder.Entity("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.Faktura", b =>
                {
                    b.Property<int>("FakturaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrojFakture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrojPonude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Cijena")
                        .HasColumnType("real");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("EksterniPrevoz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JedinicaTereta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kilometraza")
                        .HasColumnType("int");

                    b.Property<int?>("OdredisnaLokacijaID")
                        .HasColumnType("int");

                    b.Property<int?>("PolaznaLokacijaID")
                        .HasColumnType("int");

                    b.Property<float>("Tezina")
                        .HasColumnType("real");

                    b.Property<string>("TipPonude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TipPrevozaID")
                        .HasColumnType("int");

                    b.Property<int?>("ZaposlenikID")
                        .HasColumnType("int");

                    b.HasKey("FakturaID");

                    b.HasIndex("OdredisnaLokacijaID");

                    b.HasIndex("PolaznaLokacijaID");

                    b.HasIndex("TipPrevozaID");

                    b.HasIndex("ZaposlenikID");

                    b.ToTable("Faktura");
                });

            modelBuilder.Entity("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.Faktura_PoslovniPartner", b =>
                {
                    b.Property<int>("Faktura_PoslovniPartnerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FakturaID")
                        .HasColumnType("int");

                    b.Property<string>("Napomena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PoslovniPartnerID")
                        .HasColumnType("int");

                    b.HasKey("Faktura_PoslovniPartnerID");

                    b.HasIndex("FakturaID");

                    b.HasIndex("PoslovniPartnerID");

                    b.ToTable("Faktura_PoslovniPartner");
                });

            modelBuilder.Entity("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.OdredisnaLokacija", b =>
                {
                    b.Property<int>("OdredisnaLokacijaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Udaljenost")
                        .HasColumnType("int");

                    b.HasKey("OdredisnaLokacijaID");

                    b.ToTable("OdredisnaLokacija");
                });

            modelBuilder.Entity("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.PolaznaLokacija", b =>
                {
                    b.Property<int>("PolaznaLokacijaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PolaznaLokacijaID");

                    b.ToTable("PolaznaLokacija");
                });

            modelBuilder.Entity("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.PoslovniPartner", b =>
                {
                    b.Property<int>("PoslovniPartnerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BrojRealizacija")
                        .HasColumnType("int");

                    b.Property<string>("Broj_PDV_rjesenja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Broj_transakcijskog_racuna")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalji")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ID_PDV_broj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poslovna_banka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipPartnera")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PoslovniPartnerID");

                    b.ToTable("PoslovniPartner");
                });

            modelBuilder.Entity("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.Racun", b =>
                {
                    b.Property<int>("RacunID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brojracuna")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Datum_izdavanja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Opisne_stavke")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Porez")
                        .HasColumnType("real");

                    b.Property<float>("UkupnaCijena")
                        .HasColumnType("real");

                    b.HasKey("RacunID");

                    b.ToTable("Racun");
                });

            modelBuilder.Entity("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.Racun_Realizacija", b =>
                {
                    b.Property<int>("Racun_RealizacijaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datum_realizacije")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PoslovniPartnerID")
                        .HasColumnType("int");

                    b.Property<int?>("RacunID")
                        .HasColumnType("int");

                    b.Property<int?>("RealizacijaID")
                        .HasColumnType("int");

                    b.Property<int?>("ZaposlenikID")
                        .HasColumnType("int");

                    b.HasKey("Racun_RealizacijaID");

                    b.HasIndex("PoslovniPartnerID");

                    b.HasIndex("RacunID");

                    b.HasIndex("RealizacijaID");

                    b.HasIndex("ZaposlenikID");

                    b.ToTable("Racun_Realizacija");
                });

            modelBuilder.Entity("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.RadniNalog", b =>
                {
                    b.Property<int>("RadniNalogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrojPonude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrojRadnogNaloga")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Cijena")
                        .HasColumnType("real");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("EksterniPrevoz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JedinicaTereta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kilometraza")
                        .HasColumnType("int");

                    b.Property<int?>("OdredisnaLokacijaID")
                        .HasColumnType("int");

                    b.Property<int?>("PolaznaLokacijaID")
                        .HasColumnType("int");

                    b.Property<float>("Tezina")
                        .HasColumnType("real");

                    b.Property<int?>("TipPrevozaID")
                        .HasColumnType("int");

                    b.Property<int?>("ZaposlenikID")
                        .HasColumnType("int");

                    b.HasKey("RadniNalogID");

                    b.HasIndex("OdredisnaLokacijaID");

                    b.HasIndex("PolaznaLokacijaID");

                    b.HasIndex("TipPrevozaID");

                    b.HasIndex("ZaposlenikID");

                    b.ToTable("RadniNalog");
                });

            modelBuilder.Entity("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.RadniNalog_Dostavnica_Racun", b =>
                {
                    b.Property<int>("RadniNalog_Dostavnica_RacunID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DostavnicaID")
                        .HasColumnType("int");

                    b.Property<string>("Napomena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RacunID")
                        .HasColumnType("int");

                    b.Property<int?>("RadniNalogID")
                        .HasColumnType("int");

                    b.HasKey("RadniNalog_Dostavnica_RacunID");

                    b.HasIndex("DostavnicaID");

                    b.HasIndex("RacunID");

                    b.HasIndex("RadniNalogID");

                    b.ToTable("RadniNalog_Dostavnica_Racun");
                });

            modelBuilder.Entity("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.RadniNalog_PoslovniPartner", b =>
                {
                    b.Property<int>("RadniNalog_PoslovniPartnerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Napomena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PoslovniPartnerID")
                        .HasColumnType("int");

                    b.Property<int?>("RadniNalogID")
                        .HasColumnType("int");

                    b.HasKey("RadniNalog_PoslovniPartnerID");

                    b.HasIndex("PoslovniPartnerID");

                    b.HasIndex("RadniNalogID");

                    b.ToTable("RadniNalog_PoslovniPartner");
                });

            modelBuilder.Entity("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.RadniNalog_Skladiste_Vozilo", b =>
                {
                    b.Property<int>("RadniNalog_Skladiste_VoziloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datum_zaduzenja")
                        .HasColumnType("datetime2");

                    b.Property<float>("Kolicina_paleta")
                        .HasColumnType("real");

                    b.Property<int?>("RadniNalogID")
                        .HasColumnType("int");

                    b.Property<int?>("SkladisteID")
                        .HasColumnType("int");

                    b.Property<int?>("VoziloID")
                        .HasColumnType("int");

                    b.Property<int?>("ZaposlenikID")
                        .HasColumnType("int");

                    b.HasKey("RadniNalog_Skladiste_VoziloID");

                    b.HasIndex("RadniNalogID");

                    b.HasIndex("SkladisteID");

                    b.HasIndex("VoziloID");

                    b.HasIndex("ZaposlenikID");

                    b.ToTable("RadniNalog_Skladiste_Vozilo");
                });

            modelBuilder.Entity("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.Realizacija", b =>
                {
                    b.Property<int>("RealizacijaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Metoda")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RealizacijaID");

                    b.ToTable("Realizacija");
                });

            modelBuilder.Entity("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.Skladiste", b =>
                {
                    b.Property<int>("SkladisteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Datum_skladistenja")
                        .HasColumnType("datetime2");

                    b.Property<int>("Kolicina_paleta")
                        .HasColumnType("int");

                    b.Property<string>("Naziv_robe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status_robe")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkladisteID");

                    b.ToTable("Skladiste");
                });

            modelBuilder.Entity("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.TipPrevoza", b =>
                {
                    b.Property<int>("TipPrevozaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipPrevozaID");

                    b.ToTable("TipPrevoza");
                });

            modelBuilder.Entity("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.Vozilo", b =>
                {
                    b.Property<int>("VoziloID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Max_paleta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nosivost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Raspolozivost")
                        .HasColumnType("bit");

                    b.Property<string>("Registracija")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status_vozila")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vrsta")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VoziloID");

                    b.ToTable("Vozilo");
                });

            modelBuilder.Entity("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.Zaposlenik", b =>
                {
                    b.Property<int>("ZaposlenikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Broj_rjesenja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Broj_transakcijskog_racuna")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumRodjenja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JMBG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Napomena")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Poslovna_banka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pozicija")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sektor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ZaposlenikID");

                    b.ToTable("Zaposlenik");
                });

            modelBuilder.Entity("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.Faktura", b =>
                {
                    b.HasOne("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.OdredisnaLokacija", "OdredisnaLokacija")
                        .WithMany()
                        .HasForeignKey("OdredisnaLokacijaID");

                    b.HasOne("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.PolaznaLokacija", "PolaznaLokacija")
                        .WithMany()
                        .HasForeignKey("PolaznaLokacijaID");

                    b.HasOne("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.TipPrevoza", "TipPrevoza")
                        .WithMany()
                        .HasForeignKey("TipPrevozaID");

                    b.HasOne("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.Zaposlenik", "Zaposlenik")
                        .WithMany()
                        .HasForeignKey("ZaposlenikID");
                });

            modelBuilder.Entity("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.Faktura_PoslovniPartner", b =>
                {
                    b.HasOne("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.Faktura", "Faktura")
                        .WithMany()
                        .HasForeignKey("FakturaID");

                    b.HasOne("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.PoslovniPartner", "PoslovniPartner")
                        .WithMany()
                        .HasForeignKey("PoslovniPartnerID");
                });

            modelBuilder.Entity("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.Racun_Realizacija", b =>
                {
                    b.HasOne("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.PoslovniPartner", "PoslovniPartner")
                        .WithMany()
                        .HasForeignKey("PoslovniPartnerID");

                    b.HasOne("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.Racun", "Racun")
                        .WithMany()
                        .HasForeignKey("RacunID");

                    b.HasOne("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.Realizacija", "Realizacija")
                        .WithMany()
                        .HasForeignKey("RealizacijaID");

                    b.HasOne("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.Zaposlenik", "Zaposlenik")
                        .WithMany()
                        .HasForeignKey("ZaposlenikID");
                });

            modelBuilder.Entity("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.RadniNalog", b =>
                {
                    b.HasOne("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.OdredisnaLokacija", "OdredisnaLokacija")
                        .WithMany()
                        .HasForeignKey("OdredisnaLokacijaID");

                    b.HasOne("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.PolaznaLokacija", "PolaznaLokacija")
                        .WithMany()
                        .HasForeignKey("PolaznaLokacijaID");

                    b.HasOne("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.TipPrevoza", "TipPrevoza")
                        .WithMany()
                        .HasForeignKey("TipPrevozaID");

                    b.HasOne("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.Zaposlenik", "Zaposlenik")
                        .WithMany()
                        .HasForeignKey("ZaposlenikID");
                });

            modelBuilder.Entity("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.RadniNalog_Dostavnica_Racun", b =>
                {
                    b.HasOne("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.Dostavnica", "Dostavnica")
                        .WithMany()
                        .HasForeignKey("DostavnicaID");

                    b.HasOne("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.Racun", "Racun")
                        .WithMany()
                        .HasForeignKey("RacunID");

                    b.HasOne("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.RadniNalog", "RadniNalog")
                        .WithMany()
                        .HasForeignKey("RadniNalogID");
                });

            modelBuilder.Entity("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.RadniNalog_PoslovniPartner", b =>
                {
                    b.HasOne("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.PoslovniPartner", "PoslovniPartner")
                        .WithMany()
                        .HasForeignKey("PoslovniPartnerID");

                    b.HasOne("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.RadniNalog", "RadniNalog")
                        .WithMany()
                        .HasForeignKey("RadniNalogID");
                });

            modelBuilder.Entity("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.RadniNalog_Skladiste_Vozilo", b =>
                {
                    b.HasOne("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.RadniNalog", "RadniNalog")
                        .WithMany()
                        .HasForeignKey("RadniNalogID");

                    b.HasOne("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.Skladiste", "Skladiste")
                        .WithMany()
                        .HasForeignKey("SkladisteID");

                    b.HasOne("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.Vozilo", "Vozilo")
                        .WithMany()
                        .HasForeignKey("VoziloID");

                    b.HasOne("RS1_MVC_Transportno_Preduzece_core_web_app.Entiteti.Zaposlenik", "Zaposlenik")
                        .WithMany()
                        .HasForeignKey("ZaposlenikID");
                });
#pragma warning restore 612, 618
        }
    }
}
